version: '3.8'

services:
  database:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=kbcat
      - POSTGRES_DB=logomotive
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
